### ISSUE TITLE
Refactor vinti_sim (was VintiSimulationGNU) as an Octave function

### ISSUE THREAD

**Issue by G5STER** [ODU-CGA-CubeSat/orbit-propagator#20]
Inputs:

- Initial condition (state vector)
- Drag condition (e.g., tumbling, frontwise, etc.)
- Simulation length (iterations)

Outputs:

- Array of output state vectors (1 for each predicted time)
- Consider logging inputs as a flag option

Consider rewriting Mainvinti.c to read/write from/to stdin/stdout

**Comment by capsulecorplab** [comment]
some options for command line argument parsing https://stackoverflow.com/questions/9642732/parsing-command-line-arguments-in-c

**Comment by G5STER** [comment]
Done in branch new-vinti-sim
