### ISSUE TITLE
typo in repo name and cloning instructions

### ISSUE THREAD

**Issue by capsulecorplab** [ODU-CGA-CubeSat/orbit-propagator#21]
`orbit-propogator` should be `orbit-propagator` in repo name and [cloning instructions](https://github.com/ODU-CGA-CubeSat/orbit-propogator#cloning-the-repo)

**Comment by G5STER** [comment]
Closed in commit [93494f4](https://github.com/ODU-CGA-CubeSat/orbit-propagator/commit/93494f486fb444096cce34f9bf72ea6f0f1eeb5a)
